/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.biontech.view;

import com.itextpdf.text.DocumentException;
import java.awt.HeadlessException;
import java.io.IOException;
import java.sql.SQLException;

/**
 *
 * @author Prime
 */
public class FrmMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenu
     */
    public FrmMenu() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MnCliente = new javax.swing.JMenuItem();
        MnClientes = new javax.swing.JMenuItem();
        MnProdutos = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MnRealizarvendas = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        MnProdutosPdf = new javax.swing.JMenuItem();
        menu = new javax.swing.JMenu();
        MnSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BIONTECH - Área de Trabalho");
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        getContentPane().add(jDesktopPane1);

        jMenu1.setText("Cadastros");

        MnCliente.setText("Clientes");
        MnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnClienteActionPerformed(evt);
            }
        });
        jMenu1.add(MnCliente);

        MnClientes.setText("Fornecedores");
        MnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnClientesActionPerformed(evt);
            }
        });
        jMenu1.add(MnClientes);

        MnProdutos.setText("Produtos");
        MnProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnProdutosActionPerformed(evt);
            }
        });
        jMenu1.add(MnProdutos);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Movimentações");

        MnRealizarvendas.setText("Realizar Venda");
        MnRealizarvendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnRealizarvendasActionPerformed(evt);
            }
        });
        jMenu2.add(MnRealizarvendas);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Relatórios");

        MnProdutosPdf.setText("Produtos em PDF");
        MnProdutosPdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnProdutosPdfActionPerformed(evt);
            }
        });
        jMenu3.add(MnProdutosPdf);

        jMenuBar1.add(jMenu3);

        menu.setText("Sair");

        MnSair.setText("Sair");
        MnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnSairActionPerformed(evt);
            }
        });
        menu.add(MnSair);

        jMenuBar1.add(menu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnClienteActionPerformed
        new FrmCliente().setVisible(true);
    }//GEN-LAST:event_MnClienteActionPerformed

    private void MnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnClientesActionPerformed
        new FrmFornecedor().setVisible(true);
    }//GEN-LAST:event_MnClientesActionPerformed

    private void MnProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnProdutosActionPerformed
        new FrmProdutos().setVisible(true);
    }//GEN-LAST:event_MnProdutosActionPerformed

    private void MnRealizarvendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnRealizarvendasActionPerformed
        new FrmVendas().setVisible(true);
    }//GEN-LAST:event_MnRealizarvendasActionPerformed

    private void MnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_MnSairActionPerformed

    private void MnProdutosPdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnProdutosPdfActionPerformed
        // 1. Conexão com o Banco
        java.sql.Connection con = new br.com.biontech.jdbc.ConnectionFactory().getConnection();
        String sql = "SELECT * FROM produtos";

        com.itextpdf.text.Document document = new com.itextpdf.text.Document();
        
        try {

            com.itextpdf.text.pdf.PdfWriter.getInstance(document, new java.io.FileOutputStream("Relatorio_Produtos.pdf"));
            document.open();

            java.util.Date dataAgora = new java.util.Date();

            java.text.SimpleDateFormat formatador = new java.text.SimpleDateFormat("dd 'de' MMMM 'de' yyyy, 'às' HH:mm", new java.util.Locale("pt", "BR"));
            String dataFormatada = formatador.format(dataAgora);

            com.itextpdf.text.Font fonteTitulo = new com.itextpdf.text.Font(com.itextpdf.text.Font.FontFamily.HELVETICA, 18, com.itextpdf.text.Font.BOLD);
            document.add(new com.itextpdf.text.Paragraph("BIONTECH - LISTAGEM DE ESTOQUE", fonteTitulo));
            document.add(new com.itextpdf.text.Paragraph("Gerado em: " + dataFormatada)); 
            document.add(new com.itextpdf.text.Paragraph("----------------------------------------------------------------------------------------------------------------"));
            document.add(new com.itextpdf.text.Paragraph(" ")); 

            com.itextpdf.text.pdf.PdfPTable tabela = new com.itextpdf.text.pdf.PdfPTable(4);
            tabela.setWidthPercentage(100); 

            tabela.addCell("CÓDIGO");
            tabela.addCell("PRODUTO");
            tabela.addCell("PREÇO (R$)");
            tabela.addCell("ESTOQUE");

            java.sql.PreparedStatement stmt = con.prepareStatement(sql);
            java.sql.ResultSet rs = stmt.executeQuery();
            
            while(rs.next()){
                tabela.addCell(rs.getString("id"));
                tabela.addCell(rs.getString("nome"));
                tabela.addCell(rs.getString("preco_venda").replace(".", ","));
                tabela.addCell(rs.getString("estoque"));
            }
            
            document.add(tabela); 
            
            javax.swing.JOptionPane.showMessageDialog(null, "PDF Gerado com Sucesso!");

            java.awt.Desktop.getDesktop().open(new java.io.File("Relatorio_Produtos.pdf"));
            
        } catch (DocumentException | HeadlessException | IOException | SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(null, "Erro ao gerar PDF: " + e);
        } finally {
            document.close();
            try { con.close(); } catch (SQLException ex) {}
        }
    }//GEN-LAST:event_MnProdutosPdfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MnCliente;
    private javax.swing.JMenuItem MnClientes;
    private javax.swing.JMenuItem MnProdutos;
    private javax.swing.JMenuItem MnProdutosPdf;
    private javax.swing.JMenuItem MnRealizarvendas;
    private javax.swing.JMenuItem MnSair;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menu;
    // End of variables declaration//GEN-END:variables
}
